### ISSUE TITLE
Fatal error while using Lazy block on PHP 8.1

### ISSUE THREAD

**Issue by paulopmt1** [nk-crew/lazy-blocks#312]
### Issue description:
We're seeing a fatal error on `class-blocks:1387`, compatible with a tentative of counting a null object.
It fails on PHP 8.1 and works fine on PHP 7.4

### Lazy Blocks Version:
3.6.2

### WordPress Version:
6.5.2

### Any helpful information to reproduce the issue (screenshots, code parts)

Here's the complete log:

```
PHP Fatal error:  Uncaught TypeError: count(): Argument #1 ($value) must be of type Countable|array, bool given in /srv/htdocs/wp-content/plugins/lazy-blocks/classes/class-blocks.php(1387) : eval()'d code:3
Stack trace:
#0 /srv/htdocs/wp-content/plugins/lazy-blocks/classes/class-blocks.php(1387): eval()
#1 /srv/htdocs/wp-content/plugins/lazy-blocks/classes/class-blocks.php(1548): LazyBlocks_Blocks->php_eval('<?php\n$passages...', Array)
#2 /srv/htdocs/wp-content/plugins/lazy-blocks/classes/class-blocks.php(1420): LazyBlocks_Blocks->render_callback(Array, '', 'frontend')
#3 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(463): LazyBlocks_Blocks->{closure}(Array, '', Object(WP_Block))
#4 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#5 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#6 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#7 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#8 /wordpress/plugins/gutenberg/18.1.2/build/block-library/blocks/post-template.php(123): WP_Block->render(Array)
#9 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(463): gutenberg_render_block_core_post_template(Array, '<li class="wp-b...', Object(WP_Block))
#10 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#11 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#12 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#13 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#14 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#15 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#16 /wordpress/core/6.5.2/wp-includes/class-wp-block.php(443): WP_Block->render()
#17 /wordpress/core/6.5.2/wp-includes/blocks.php(1705): WP_Block->render()
#18 /wordpress/core/6.5.2/wp-includes/blocks.php(1743): render_block(Array)
#19 /wordpress/core/6.5.2/wp-includes/block-template.php(260): do_blocks('<!-- wp:templat...')
#20 /wordpress/core/6.5.2/wp-includes/template-canvas.php(12): get_the_block_template_html()
#21 /wordpress/core/6.5.2/wp-includes/template-loader.php(106): include('/wordpress/core...')
#22 /wordpress/core/6.5.2/wp-blog-header.php(19): require_once('/wordpress/core...')
#23 /wordpress/core/6.5.2/index.php(17): require('/wordpress/core...')
#24 {main}
  thrown in /srv/htdocs/wp-content/plugins/lazy-blocks/classes/class-blocks.php(1387) : eval()'d code on line 3

```

**Comment by nk-o** [comment]
Hi,

The problem probably originates from your custom block code. Please consult a similar error code on our troubleshooting page: https://www.lazyblocks.com/docs/troubleshooting/receive-an-error-type-e-error-eval/.

Regards,
Nikita.
